### ISSUE TITLE
CRUD API for Notes Database

### ISSUE THREAD

**Issue by GavinZhengOI** [agiledev-students-fall2024/4-final-project-easynote#19]
Related to User Story #1 

It should support:

- Create a note
- Read a note
- Update a note
- Delete a note

**Comment by YONGSIGU** [comment]
I finish this task, beside, I also find the user CRUD, and login api. (or else I cannot test note api)

**Comment by GavinZhengOI** [comment]
> I finish this task, beside, I also find the user CRUD, and login api. (or else I cannot test note api)

Thanks Zuyan, could you open a PR?
